### PR TITLE
provide https and auth

### LINKED ISSUE #37: [Enhancement] Enable HTTPS and Auth like in RPC
see https://github.com/ioBroker/ioBroker.hm-rpc/issues/94
The https ports are are the same as usual expect that they start with an additional 4.

### PR DESCRIPTION
**Pull request by foxriver76**
-https front and backend
-auth front and backend
-enhanced rega lib to handle auth
-minor changes
-preapred 1.8.0
-closes #37

### CODE REVIEW

**Comment by Apollon77** [comment]
wat exactly breaks nodejs 4?

**Comment by foxriver76** [comment]
Arrow functions, const, can replace it but we want to remove node4 support anyway I think

**Comment by Apollon77** [comment]
An please add the minimum node version in package.json! So that people with nodejs 4 that try to install it will get directly an error and no changes

**Comment by foxriver76** [comment]
Will do it this evening

**Comment by Apollon77** [comment]
tell me when mergable

**Comment by foxriver76** [comment]
It is ready for merge.

**Comment by Apollon77** [comment]
one thing I saw in review ... The admin index uses 

```
for (var key in settings) {
```
to init all fields. Problem with this is that it happends that new fields (like in this commit 3 of them) are undefined sometime and then this field is not triggering the buttonchange and such.
So check for "undefined" fields and init them before that loop or iterate over the "html fields" (e.g. like https://github.com/Apollon77/ioBroker.tuya/blob/master/admin/index_m.html#L58) then you always have all fields ...

**Comment by foxriver76** [comment]
Thanks, will check and add it

**Comment by Apollon77** [comment]
he chose the easy way ;-)) everthing ok

**Comment by foxriver76** [comment]
frontend :-1:

**Comment by Apollon77** [comment]
Merged, Would you be so kind and open a forum testing thread?!

**Comment by foxriver76** [comment]
Yes I will open one. you know how to challenge me. Implemented it the more elegant way in hm-rpc :laughing:

**Comment by Apollon77** [comment]
;-)))
Nur an Herausforderungen wächst man" *duck*

**Pull request merged**
