### PR TITLE
added stopBeforeUpdate

### PR DESCRIPTION
**Pull request by simatec**

### CODE REVIEW

**Comment by foxriver76** [comment]
Thank you for the comprehensive description.

**Comment by foxriver76** [comment]
Not used by controller not in the docs so what is the purpose of this flag..

**Comment by foxriver76** [comment]
Ah found it https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

**Comment by GermanBluefox** [comment]
I have the same question now.

**Comment by simatec** [comment]
After each update I found that the instance does not end immediately after the update and errors occur afterwards, that the instance is already running.  backitup also had this problem at the time.  so I stop the instances before the update and then start again.  In my case, I was able to determine that this prevents the instances from starting twice

**Comment by GermanBluefox** [comment]
But I would say, that this is bug in js-controller....

**Comment by simatec** [comment]
OK, thanks for the feedback @GermanBluefox

**Comment by Apollon77** [comment]
@simatec could you please create a issue for conteoller that we can check it?

**Pull request closed without merging**
