### PR TITLE
just a small fix

### PR DESCRIPTION
**Pull request by f-israel**
Had a situation (iobroker+debmatic on local) where I couldn't use default port. After investigating I found out that checkrega.cgi and rega.exe were not sharing same port. Most likely I'd a config bug but still just added the features.

As commit message says:
fixed https checkbox disabling authentication fields
split error "CCU unreachable" into "CCU rega.exe unreachable" and "CCU UI unreachable"

### CODE REVIEW

**Comment by Apollon77** [comment]
The authentication fields being disabled when no https is used was there by intend because there is no point in using credentials but transfer them unencrypted. then just do not use authentication.

The other change seems to make things more complex for a really special case like your configuration error ...

Thank you very much for your work, but my spontan thought would be to decline this PR ...

@foxriver76 What do you think?

**Comment by f-israel** [comment]
> 
> 
> The authentication fields being disabled when no https is used was there by intend because there is no point in using credentials but transfer them unencrypted. then just do not use authentication.
> 
You've got a point there. In my case just the iob is connecting via localhost. Any other device (e.g. the real clients) access via ssl secured reverse proxy. I didn't found a way to bypass rega auth when origin is localhost only. 

Regarding the port setting I guess it could be reduced to single port (just seeing default CCU using 80/443; piVCCU,etc. 8181 or configured). Some preperations were already made (see .homematicPort) but missing in hm-rega.js. Just to be sure: Was is initially intentionally to force the checkrega.cgi/webui requests to default ports only?

Don't get me wrong here: Just trying to find out which changes are regarded as "to keep".

**Comment by foxriver76** [comment]
Regarding changes of frontend auth checkbox:

this is absolutely intended and I do not see a reason to change this. This prevents less experienced users from transmitting their credentials in clear text. For edge cases like your scenario I refer to the cli, where it is still possible to set the credentials, because there is only frontend validation. Also I recognized, that you can activate auth, set credentials, deactivate and adapter should use the credentials. However, this is not intended and will be removed, thus unchecking auth will delete credentials in the future. Setting credentials via cli will stay and follows style of admin adapter, where you can also use credentials w.o. auth only by setting it by cli/changing system.adapter.. object.

Regarding port selection:
It is currently also possible to change the port via cli by setting homematicPort. But if https is enabled, port is set to 48181 fixed, I will change this and will also think about adding the port to frontend (or at least documenting how to change by cli). The thing with different ports (web/api) is probably overkill and adds lots of weirdness to the user, also you mentioned that its probably unnecessary either.

Offtopic for future PRs etc: When translating, stuff in words.js you can get missing languages via https://translator.iobroker.in and when adding new config attributes they should also be added to the `native` part of io-package.json

**Comment by f-israel** [comment]
Well thanks for response so far. With respect to your arguments I'm convinced this PR shouldn't be merged. You gave me quite interesting points I didn't know about. I guess it's enough to document the CLI way for changing or at least point at the possibility - had I found this one I would have saved a lot of time. Guess I'll not be the last one needing this.

**Comment by foxriver76** [comment]
Another point which is maybe interesting for you if you only want to have local access to your CCU (assuming an up-to-date CCU or Raspberrymatic, for other emulations I am not sure): 

- You can basically restrict every port in the CCU firewall which makes it not accessible from anyone else than localhost
- Default: Port 38181 (rega) is accessible by localhost w/o authentication even if auth is turned on on your CCU, same for 32001 (rfd), 32010 (hmip)

Anyway, thanks four your work and patience.

**Pull request closed without merging**
